name: env_dws_processing
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - xarray
  - netCDF4
  - requests
  - scikit-image
  - python-dateutil
  - matplotlib
  - scipy
  - pyproj
  - pip